### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by pet1330** [ZYinMD/domain-fullscreen-for-googletasks#1]
Hi, 

Would it be possible to make the extension window a PWA, so that it can be installed as a "standalone application" and can also have a different Icon instead of just the chrome icon, etc?

If you make it public, I'm happy to help.

Thanks

**Comment by ZYinMD** [comment]
Hi, are you on mac or windows?

**Comment by pet1330** [comment]
Neither, I'm on Linux (Ubuntu Specifically)

**Comment by ZYinMD** [comment]
I'm actually very curious how the application icon behaves in Linux in these two conditions:

1. if you click the gear button, and choose "standalone app"
2. if you follow the steps in Q4 in the FAQ to create a "chrome app"

In the 2 cases above, respectively, does this app appear in the launcher? Does it have its own icon or just use the chrome icon? If it uses the chrome icon, does it stack together with chrome?

**Comment by pet1330** [comment]
When you just open it normally as a chrome extension, it does not stack with other chrome tabs, but does share the same standard chrome icon:

![Screenshot from 2020-03-24 18_16_57](https://user-images.githubusercontent.com/4920245/77462368-f43bcc80-6dfb-11ea-864f-99f93dee0d8a.png)

When opened in stand-alone mode, it looks like this:

![Screenshot from 2020-03-24 18_23_39](https://user-images.githubusercontent.com/4920245/77463070-f05c7a00-6dfc-11ea-85c9-2dcd0f84fe81.png)

and when you follow the FAQ, you do get the favicon icon as the desktop, but not in the sidebar icon.

![Screenshot from 2020-03-24 18_28_13](https://user-images.githubusercontent.com/4920245/77463346-6234c380-6dfd-11ea-9eff-68651f777496.png)

If you make it a PWA served over https, you can specify the application icon and run it as a standalone application. For example, my website is a PWA and when I install it, it shows the icon when used in stand-alone mode, but the chrome icon stacked when opened in a normal tab.

![image](https://user-images.githubusercontent.com/4920245/77464179-b3918280-6dfe-11ea-9b5c-23e6f9b368ce.png)

(chrome app left, chrome tab right)

![image](https://user-images.githubusercontent.com/4920245/77464363-f5bac400-6dfe-11ea-9331-84713bbd33b5.png)

I've never built a chrome extension though, so I'm not entirely sure if you can make a chrome extension a PWA?

It's probably also worth noting that the images above are from the Unity Desktop interface, I have also checked on Gnome and it's exactly the same, except that your chrome icon is stacked with other chrome windows :smile:

**Comment by ZYinMD** [comment]
Thanks so much for your detailed tests and screenshots! 

1. the icon:

On Window and Mac , when I firsted started this project in mid 2019, the icon didn't work very well. Then sometime in late 2019, the icon suddenly became good. Right now both Window and Mac displays the proper icon on the Taskbar / Dock.

My guess is the Chrome team is actively working on it, and it *may* come to Linux soon (although it could also be something on the Unity side, I'm not sure). One way to test is install Chrome Canary ( = Chrome version +2, currently v83), and see if it makes any difference, especially the "chrome app" icon created in the way mentioned in the FAQ.

2. PWA:

I do have plans to make a PWA version of this app, but unfortunately it can't be done very easily, because of some chrome APIs it used, especially the OAuth part. It'll probably involve forking the codebase, make lots of changes scattered in many files, then launch it as a new website.

3. open source it:

My plan was to open it if I can't get very popular within one year after launch, which is October 2020. I'll keep you posted.

Thanks!
